#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${ENGINE_BUILD_DIR:-$ROOT_DIR/build}"
BUILD_TYPE="${CMAKE_BUILD_TYPE:-Debug}"
CXX_STANDARD="${CMAKE_CXX_STANDARD:-20}"
REDPANDA_PORT="${E2E_REDPANDA_PORT:-19092}"
MINIO_PORT="${E2E_MINIO_PORT:-59000}"
MARKETS_CONFIG="${CEX_ENGINE_MARKETS_CONFIG:-$ROOT_DIR/test-harness/exchange-e2e-markets.conf}"

if [[ ! -f "$MARKETS_CONFIG" ]]; then
  echo "missing engine markets config: $MARKETS_CONFIG" >&2
  exit 1
fi

cmake -S "$ROOT_DIR" -B "$BUILD_DIR" \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DCMAKE_CXX_STANDARD="$CXX_STANDARD" \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
cmake --build "$BUILD_DIR" --target engine_app --parallel

exec env \
  CEX_ENGINE_BOOTSTRAP_SERVERS="${CEX_ENGINE_BOOTSTRAP_SERVERS:-127.0.0.1:${REDPANDA_PORT}}" \
  CEX_ENGINE_CHECKPOINT_STORE="${CEX_ENGINE_CHECKPOINT_STORE:-s3}" \
  CEX_ENGINE_CHECKPOINT_S3_ENDPOINT="${CEX_ENGINE_CHECKPOINT_S3_ENDPOINT:-http://127.0.0.1:${MINIO_PORT}}" \
  CEX_ENGINE_CHECKPOINT_S3_BUCKET="${CEX_ENGINE_CHECKPOINT_S3_BUCKET:-exchange-checkpoints}" \
  CEX_ENGINE_CHECKPOINT_S3_ACCESS_KEY="${CEX_ENGINE_CHECKPOINT_S3_ACCESS_KEY:-minioadmin}" \
  CEX_ENGINE_CHECKPOINT_S3_SECRET_KEY="${CEX_ENGINE_CHECKPOINT_S3_SECRET_KEY:-minioadmin}" \
  CEX_ENGINE_CHECKPOINT_S3_REGION="${CEX_ENGINE_CHECKPOINT_S3_REGION:-us-east-1}" \
  CEX_ENGINE_MARKETS_CONFIG="$MARKETS_CONFIG" \
  "$BUILD_DIR/engine_app"
